# This is a basic workflow to help you get started with Actions
name: CI/CD
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev, new_version ]
  pull_request:
    branches: [ dev, new_version ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build job
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '18.x'
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm install  --legacy-peer-deps
      # Runs a set of commands to build
      - name: Build
        run: npm run build
        
      # Store the artifact
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: ./dist
      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
      
      # Deploy documentation
      - name: Build docs
        run: npm run docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN_GH_PAGES }}
          folder: documentation

